name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  PushReadmeJob:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: davidelanz/jupytorch
          provider: dockerhub
          short_description: "Quickly set up Pytorch and Jupyter Lab"
          readme_file: "README.md"

  BuildPushCPU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: davidelanz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cpu
          tags: davidelanz/jupytorch:cpu

  BuildPushGPU:
    runs-on: ubuntu-latest
    name: GPU
    strategy:
      fail-fast: false
      matrix:
        include:
          # CUDA 10
          - cuda: "10.0"
            cudnn: "7"
          - cuda: "10.1"
            cudnn: "7"
          - cuda: "10.1"
            cudnn: "8"
          - cuda: "10.2"
            cudnn: "7"
          - cuda: "10.2"
            cudnn: "8"
          # CUDA 11
          - cuda: "11.0.3"
            cudnn: "8"
          - cuda: "11.1.1"
            cudnn: "8"
          - cuda: "11.2.2"
            cudnn: "8"
          - cuda: "11.3.0"
            cudnn: "8"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: davidelanz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: gpu
          build-args: |
            CUDA_VERSION=${{ matrix.cuda }}
            CUDNN_VERSION=${{ matrix.cudnn }}
          tags: davidelanz/jupytorch:gpu-cuda${{ matrix.cuda }}-cudnn${{ matrix.cudnn }}
