name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  PushReadmeJob:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: davidelanz/jupytorch
          provider: dockerhub
          short_description: "Quickly set up Pytorch and Jupyter Lab"
          readme_file: "README.md"

  BuildPushCPU:
    runs-on: ubuntu-latest
    name: CPU
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Build and push CPU image
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS && \
          docker build . \
            --file cpu/Dockerfile \ 
            --tag davidelanz/jupytorch:cpu && \
          docker push davidelanz/jupytorch:cpu

  BuildPushGPU:
    runs-on: ubuntu-latest
    name: GPU
    strategy:
      fail-fast: false
      matrix:
        include:
          # CUDA 10
          - cuda: '10.1'
            cudnn: '7'
            cudatlk: '10.1'
          - cuda: '10.1'
            cudnn: '8'
            cudatlk: '10.1'
          - cuda: '10.2'
            cudnn: '7'
            cudatlk: '10.2'
          - cuda: '10.2'
            cudnn: '8'
            cudatlk: '10.2'
          # CUDA 11
          - cuda: '11.1.1'
            cudnn: '8'
            cudatlk: '11.1'
          - cuda: '11.2.2'
            cudnn: '8'
            cudatlk: '11.1'
            experimental: true
          - cuda: '11.3.0'
            cudnn: '8'
            cudatlk: '11.1'
            experimental: true
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Build and push GPU images
        env:
          DOCKER_USER: davidelanz
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run:  | 
          docker login -u $DOCKER_USER -p $DOCKER_PASS && \
          docker build . \
            --build-arg CUDA_VERSION=${{ matrix.cuda }}  \
            --build-arg CUDNN_VERSION=${{ matrix.cudnn }} \
            --build-arg CUDA_TOOLKIT=${{ matrix.cudatlk }} \
            --file gpu/Dockerfile \
            --tag davidelanz/jupytorch:gpu-cuda${{ matrix.cuda }}-cudnn${{ matrix.cudnn }} && \
          docker push davidelanz/jupytorch:gpu-cuda${{ matrix.cuda }}-cudnn${{ matrix.cudnn }}
